export const APPLICATION_STATUS = Object.freeze({
  INSPECTION_SCHEDULED: 'INSPECTION_SCHEDULED',
  INSPECTION_VERIFIED: 'INSPECTION_VERIFIED',
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
});

export const INSPECTION_STATUS = Object.freeze({
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  SCHEDULED: 'SCHEDULED',
  NO_SHOW: 'NO_SHOW',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED'
});

export const TENANCY_STATUS = Object.freeze({
  PENDING_MOVE_IN: 'PENDING_MOVE_IN',
  ACTIVE: 'ACTIVE',
  ENDED: 'ENDED'
});

export const MAINTENANCE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED'
});

export const PAYMENT_STATUS = Object.freeze({
  PAID: 'PAID',
  PENDING: 'PENDING',
  OVERDUE: 'OVERDUE',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
});
